package com.example.listycity;

import android.app.AlertDialog;
import android.app.Dialog;
import android.content.Context;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.EditText;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.DialogFragment;

// Reuse the addCityFragment class from above
public class EditCityFragment extends DialogFragment {
    interface EditCityDialogListener {
        void editCity(String newCityName, String newProvinceName);
    }

    private EditCityDialogListener listener;

    @Override
    public void onAttach(@NonNull Context context) {
        super.onAttach(context);

        if (context instanceof EditCityDialogListener) {
            listener = (EditCityDialogListener) context;
        } else {
            throw new RuntimeException(context + " must implement AddCityDialogListener");
        }
    }

    // Factory method to create fragment with existing city data
    public static EditCityFragment newInstance(City city) {
        Bundle args = new Bundle();
        args.putString("cityName", city.getName());
        args.putString("provinceName", city.getProvince());

        EditCityFragment fragment = new EditCityFragment();
        fragment.setArguments(args);
        return fragment;
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(@Nullable Bundle savedInstanceState) {
        View view = LayoutInflater.from(getContext()).inflate(R.layout.fragment_add_city, null);
        EditText editCityName = view.findViewById(R.id.edit_text_city_text);
        EditText editProvinceName = view.findViewById(R.id.edit_text_province_text);
        AlertDialog.Builder builder = new AlertDialog.Builder(getContext());

        // The following if-statement was generated by Gemini 3, Google DeepMind
        // As a prompt I gave it my code from this file and MainActivity.java and said
        // "I have the getters/setters implemented in the CIty class, here is my ___ file ..."
        // 26/01/21 4:29pm
        if (getArguments() != null) {
            editCityName.setText(getArguments().getString("cityName"));
            editProvinceName.setText(getArguments().getString("provinceName"));
        }

        return builder
                .setView(view)
                .setTitle("Edit city info")
                .setNegativeButton("Cancel", null)
                .setPositiveButton("Confirm", (dialog, which) -> {
                    String cityName = editCityName.getText().toString();
                    String provinceName = editProvinceName.getText().toString();
                    listener.editCity(cityName, provinceName);
                })
                .create();
    }
}
