package com.example.listycity;

import android.graphics.Color;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.floatingactionbutton.FloatingActionButton;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity implements AddCityFragment.AddCityDialogListener, EditCityFragment.EditCityDialogListener{

    private ArrayList<City> dataList;
    private ListView cityList;
    private CityArrayAdapter cityAdapter;

    // Variable to track which city was clicked
    int selectedIdx = -1;
    // Variable to visually track which city was clicked
    View selectedView = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        String[] cities = { "Edmonton", "Vancouver", "Toronto" };
        String[] provinces = { "AB", "BC", "ON" };

        dataList = new ArrayList<>();
        for (int i = 0; i < cities.length; i++) {
            dataList.add(new City(cities[i], provinces[i]));
        }

        cityList = findViewById(R.id.city_list);
        cityAdapter = new CityArrayAdapter(this, dataList);
        cityList.setAdapter(cityAdapter);

        FloatingActionButton fab = findViewById(R.id.button_add_city);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new AddCityFragment().show(getSupportFragmentManager(), "Add City");
            }
        });

        // Event listener for clicks on the list items (cities)
        cityList.setOnItemClickListener(new ListView.OnItemClickListener(){
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                selectedIdx = position;
                selectedView = view;

                // Change background color to show it has been selected
                view.setBackgroundColor(Color.LTGRAY);

                // Add pop-up (fragment) to prompt user to edit
                // Reuse fragment from adding city
                // Creates newInstance and passes selected city into fragment
                new EditCityFragment().newInstance(dataList.get(selectedIdx)).show(getSupportFragmentManager(), "Edit City Information");
            }
        });
    }

    @Override
    public void addCity(City city) {
        dataList.add(city);
        cityAdapter.notifyDataSetChanged();
    }

    @Override
    public void editCity(String newName, String newProvince) {
        // Get element at selected index and then change the city and province
        dataList.get(selectedIdx).setName(newName);
        dataList.get(selectedIdx).setProvince(newProvince);
        cityAdapter.notifyDataSetChanged();

        // Change color of selected city back to default
        if (selectedView != null) {
            // The following line was generated by Gemini 3, Google DeepMind,
            // Prompt: "how do I get this using view.setBackgroundColor(Color.LTGRAY);, I don't need grey just completely transparent"
            // 26/01/21, 3:59pm
            selectedView.setBackgroundColor(Color.TRANSPARENT);
        }

    }
}